<<<<<<< HEAD
spring:
=======
server:
  port: 8080
  forward-headers-strategy: native
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
>>>>>>> 5d3cee2 (initial commit after .git removal)
  application:
    name: tododok
  #.env 파일에서 환경변수 불러오기
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
<<<<<<< HEAD

custom:
=======
management:
  endpoints:
    web:
      base-path: /actuator            # 기본값이지만 명시
      exposure:
        include: health,info          # 필요시 metrics 등 추가
  endpoint:
    health:
      probes:
        enabled: true                 # /actuator/health/{liveness,readiness} 활성화
      show-details: never             # 프로브 용도면 never 권장(민감정보 차단)
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: tododuk.flatcheese.com
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: flatcheese(dev)
>>>>>>> 5d3cee2 (initial commit after .git removal)
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*60*24}"
push:
  vapid:
    publicKey: 'BFRV6aGPQG4sFZbQaXcU4z1FpHGsbhMnC5KfSZSJKOA3irDOXJxLKsskeVO8fptRZgAfo9V2c-1bgjqp8yw373s'
    privateKey: '2RH-wiOHKbuoY0gAD775bOoXmnbsSTrpgVkQzGvBh9c'